Attribute VB_Name = "Module2"
Public Which_Tab_am_I_On As Integer
Public NumPopup_ConfigFastBTIStress As Integer
Public Store_Slot_IndexNumber(35) As String
Public Store_Channel_IndexNumber(35) As String
Public Channel_1_DUT1 As String
Public Channel_2_DUT1 As String
Public Channel_3_DUT1 As String
Public Channel_4_DUT1 As String
Public Channel_1_DUT2 As String
Public Channel_2_DUT2 As String
Public Channel_3_DUT2 As String
Public Channel_4_DUT2 As String
Public Channel_1_DUT3 As String
Public Channel_2_DUT3 As String
Public Channel_3_DUT3 As String
Public Channel_4_DUT3 As String
Public Channel_1_DUT4 As String
Public Channel_2_DUT4 As String
Public Channel_3_DUT4 As String
Public Channel_4_DUT4 As String
Public Channel_1_DUT5 As String
Public Channel_2_DUT5 As String
Public Channel_3_DUT5 As String
Public Channel_4_DUT5 As String
Public Channel_1_DUT6 As String
Public Channel_2_DUT6 As String
Public Channel_3_DUT6 As String
Public Channel_4_DUT6 As String
Public Channel_1_DUT7 As String
Public Channel_2_DUT7 As String
Public Channel_3_DUT7 As String
Public Channel_4_DUT7 As String
Public Channel_1_DUT8 As String
Public Channel_2_DUT8 As String
Public Channel_3_DUT8 As String
Public Channel_4_DUT8 As String
Public Channel_1_DUT9 As String
Public Channel_2_DUT9 As String
Public Channel_3_DUT9 As String
Public Channel_4_DUT9 As String
Public C901ValueStored As Integer
Public C902ValueStored As Integer
Public C801ValueStored As Integer
Public C802ValueStored As Integer
Public C701ValueStored As Integer
Public C702ValueStored As Integer
Public C601ValueStored As Integer
Public C602ValueStored As Integer
Public C501ValueStored As Integer
Public C502ValueStored As Integer
Public StoreTotNumActiveChannels As Integer



